<div class="container smaller_container">
    <div class="row">
        <div class="line_wrapper clearfix">
            <p class="copyright">© Viparis 2016</p>
            <ul>
                <li><a href="<?php echo $this->getHref('#'); ?>">A propos de Viparis</a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>">Crédits & mentions légales</a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>">Cookies</a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>">CGV - CGU</a></li>
                <li class="hide_in_tablet"><a href="#">CGS</a></li>
            </ul>
        </div>
    </div>
</div>
