<div class="filter_block">
    <h3 class="filter_block_titel">votre Sélection</h3>
    <div id="filter_accordeon">
        <div class="accordeon_body">
            <div class="seller_wrap">
                <p class="about_seller">Vendeur n°1</p>
                <div class="remove_seller">
                    <span class="seller_cross"></span>
                </div>
            </div>
            <div class="seller_wrap">
                <p class="about_seller">Vendeur numéro trois <span>sur 2 deux lignes</span></p>
                <div class="remove_seller">
                    <span class="seller_cross"></span>
                </div>
            </div>
        </div>
        <p class="accordeon_top_head"><span class="head_inside">Catégories</span></p>
        <p class="accordeon_head"><span class="head_inside">prix</span></p>
        <div class="accordeon_body">
            222
        </div>
        <p class="accordeon_head"><span class="head_inside without_border">Vendeur</span></p>
        <div class="accordeon_body">
            <div class="check_seller_wrap">
                <input type="checkbox" class="seller_checkbox">
                <p class="seller_name">Vendeur n°1</p>
                <span class="count_of_seller">(12)</span>
            </div>
            <div class="check_seller_wrap">
                <input type="checkbox" class="seller_checkbox">

                <p class="seller_name">Vendeur numéro 2</p>
                <span class="count_of_seller">(28)</span>
            </div>
            <div class="check_seller_wrap">
                <input type="checkbox" class="seller_checkbox">
                <p class="seller_name">Vendeur numéro trois sur <span>2 deux lignes</span></p>
                <span class="count_of_seller">(17)</span>
            </div>
            <div class="check_seller_wrap">
                <input type="checkbox" class="seller_checkbox ">
                <p class="seller_name">Vendeur n°4</p>
                <span class="count_of_seller">(53)</span>
            </div>
        </div>
    </div>
    <div class="filter_info_wrap">
        <div class="titel_wrap">
            <img src="./" alt="line" class="titel_img">
            <h3 class="info_titel">Réalisez le plan de vote stand</h3>
        </div>
        <p class="main_info">Les produits électriques nécessitent que vous complétiez le plan à transmettre lors de la commande pour réaliser l'installation.</p>
        <a href="#" class="info_link">Télécharger le gabarit du plan</a>
    </div>
</div>