<div class="row dates_row">
    <div class="col-lg-5 col-md-12">
        <div class="top_left">
            <p class="interval"><span>Palais des Congrès de Paris</span>  du 01/10/2016 au 16/11/2016 </p>
        </div>
    </div>
    <div class="col-lg-7 col-md-12">
        <div class="top_right">
            <p class="date first_date">Fermeture catalogue <span>jj/mm/aaaa</span></p>
            <p class="date second_date">Date de majoration <span>jj/mm/aaaa</span></p>
        </div>
    </div>
</div>