<div class="quotation_wrapper">
    <div class="quotation clearfix">
        <div class="quotation_left-content">
            <h4 class="quotation_titel">devis</h4>
            <p class="quotation_text quotation_text_top">Aucun produit ne correspond à votre recherche</p>
            <p class="quotation_text">Un besoin sur mesure ou une demande de prestation</p>
        </div>
        <a href="#" class="quotation_button">demandez <span>un devis</span></a>
    </div>
</div>