<div class="article_block">
    <div class="settings_wrap">
        <div class="col-xs-2 count_wrap">
            <p class="article_count"><span>137</span> produits</p>
        </div>
        <div class="col-xs-10">
            <div class="more_settings">
                <select name="quantity_select" id="sort_by_quantity">
                    <option value="10 par page">10 par page</option>
                    <option value="10 par page">10 par page</option>
                    <option value="10 par page">10 par page</option>
                    <option value="10 par page">10 par page</option>
                </select>
                <select name="prise_select" id="sort_by_prise">
                    <option value="Le plus cher">Le plus cher</option>
                    <option value="Le plus cher">Le plus cher</option>
                    <option value="Le plus cher">Le plus cher</option>
                    <option value="Le plus cher">Le plus cher</option>
                </select>
                <div class="view_wrap">
                    <div class="views">
                        <div class="inner_views in_lines"></div>
                    </div>
                    <div class="views">
                        <div class="inner_views in_cols"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>