<div class="container smaller_container">
    <div class="row">
        <div class="col-md-12 col-lg-6">
            <div class="middle_footer__main_col">
                <div class="col-lg-6 col-sm-3">
                    <div class="main_col__servises">
                        <h3>premier <span>salon</span></h3>
                        <a href="<?php echo $this->getHref('#'); ?>">Les informations clés</a>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-3 third">
                    <div class="main_col__servises">
                        <h3>Liste <span>d’achats</span></h3>
                        <a href="<?php echo $this->getHref('#'); ?>">Réservez avant<span>de commander</span></a>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-3 second">
                    <div class="main_col__servises">
                        <h3>Service <span>exposants</span></h3>
                        <a href="<?php echo $this->getHref('#'); ?>">Les conseils <span>de nos experts</span></a>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-3 forth">
                    <div class="main_col__servises">
                        <h3>Devenir <span>prestataire</span></h3>
                        <a href="<?php echo $this->getHref('#'); ?>">Donnez de la visibilité <span>à vos produits</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-6">
            <div class="middle_footer__main_col">
                <div class="col-lg-6 col-sm-4">
                    <div class="main_col__call_back">
                        <h3>Lettre d’information</h3>
                        <p>Etre alerté des avantages & nouveautés</p>
                        <form action="">
                            <input class="textField" type="text" placeholder="Votre adresse mail">
                            <input type="submit" class="iButton" value="OK">
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-3 third">
                    <div class="main_col__other_links">
                        <div class="other_links__wrap">
                            <h3>Sites du groupe</h3>
                            <p>Découvrez notre groupe</p>
                            <a href="#" class="other_links__link">viparis.com</a>
                            <a href="#" class="other_links__link">venuesinparis.com</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-5 second">
                    <div class="main_col__social">
                        <div class="social__social_wrap">
                            <h3>Viparis social</h3>
                            <p>Restez connecter sur les réseaux sociaux</p>
                            <ul class="social__socialIcon">
                                <li><a href="#" class="social__fIcon"></a></li>
                                <li><a href="#" class="social__tIcon"></a></li>
                                <li><a href="#" class="social__yIcon"></a></li>
                                <li><a href="#" class="social__inIcon"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>