<div class="filter_info_wrap">
    <div class="titel_wrap">
        <img src="<?php echo $this->getViewFileUrl('images/line.png'); ?>" alt="line" class="titel_img">
        <h3 class="info_titel">Réalisez le plan de vote stand</h3>
    </div>
    <p class="main_info">Les produits électriques nécessitent que vous complétiez le plan à transmettre lors de la commande pour réaliser l'installation.</p>
    <a href="<?php echo $this->getHref('#'); ?>" class="info_link">Télécharger le gabarit du plan</a>
</div>
