<div class="container smaller_container">
    <div class="row">
        <div class="col-sm-3 top_footer__item">
            <a href="<?php echo $this->getHref('#'); ?>" class="item__answers">Besoin d'aide ?</a>
        </div>
        <div class="col-sm-9 top_footer__item">
            <ul class="item__useful_inks">
                <li><a href="<?php echo $this->getHref('#'); ?>"><span class="img faq"></span> <span>faq</span></a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>"><span class="img tchat"></span> <span>tchat</span></a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>"><span class="img appeler"></span> <span>appeler</span></a></li>
                <li><a href="<?php echo $this->getHref('#'); ?>"><span class="img contact"></span> <span>contact</span></a></li>
            </ul>
        </div>
    </div>
</div>
