<div class="breadcrumbs_wrapper">
    <ul class="breadcrumbs">
        <li class="breadcrumbs__item"><a href="<?php echo $this->getHref('#'); ?>" class="breadcrumbs__link">Accueil</a></li>
        <li class="breadcrumbs__item"><span class="breadcrumbs__last">Présentation</span></li>
    </ul>
</div>
<div class="row">
    <div class="col-lg-5 col-md-12">
        <div class="top_left">
            <p class="interval"><span>Palais des Congrès de Paris</span>  du 01/10/2016 au 16/11/2016 </p>
        </div>
    </div>
    <div class="col-lg-7 col-md-12">
        <div class="top_right">
            <p class="date first_date">Fermeture catalogue <span>jj/mm/aaaa</span></p>
            <p class="date second_date">Date de majoration <span>jj/mm/aaaa</span></p>
        </div>
    </div>
</div>
<h1 class="top_main_titele">éléctricité</h1>
