<div class="main_col">
    <div>
        <div class="servises">
            <h3>premier salon</h3>
            <a href="#">Les informations clés</a>
        </div>
    </div>
    <div class="third">
        <div class="servises">
            <h3>Liste d’achats</h3>
            <a href="#">Réservez avant<span>de commander</span></a>
        </div>
    </div>
    <div class="second">
        <div class="servises">
            <h3>Service exposants</h3>
            <a href="#">Les conseils <span>de nos experts</span></a>
        </div>
    </div>
    <div class="forth">
        <div class="servises">
            <h3>Devenir prestataire</h3>
            <a href="#">Donnez de la visibilité <span>à vos produits</span></a>
        </div>
    </div>
</div>