<div class="second">
    <div class="social">
        <div class="social_wrap">
            <h3>Viparis social</h3>
            <p>Restez connecter sur les réseaux sociaux</p>
            <ul class="socialIcon">
                <li><a href="#" class="fIcon"></a></li>
                <li><a href="#" class="tIcon"></a></li>
                <li><a href="#" class="yIcon"></a></li>
                <li><a href="#" class="inIcon"></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="third">
    <div class="otherLinks">
        <div class="other_wrap">
            <h3>Sites du groupe</h3>
            <p>Découvrez notre groupe</p>
            <a href="#" class="link">viparis.com</a>
            <a href="#" class="link">venuesinparis.com</a>
        </div>
    </div>
</div>
